"""
Translation Engine: IR (JSON)  ->  runnable pytest + Selenium code.

DELIBERATELY NOT an LLM. This is template-based, deterministic codegen.
The LLM produces the IR; this renders IR to code. That separation means
the generated test scripts are predictable, auditable, and diff-able --
which is non-negotiable for a security-testing product.
"""
from __future__ import annotations

from taas.ir.schema import TestSuite, TestCase, TestStep, ActionType
from taas.ir.validator import IRValidator


class IRValidationError(Exception):
    """Raised when codegen is attempted on IR that failed validation."""
    def __init__(self, result):
        self.result = result
        lines = [f"{i.path}: {i.code} — {i.message}" for i in result.errors]
        super().__init__("Cannot generate code; IR has errors:\n  " +
                         "\n  ".join(lines))


class SeleniumTranslator:

    def render_suite(self, suite: TestSuite, *, validate: bool = True) -> str:
        # Hard gate: never emit Selenium from invalid IR. This is the line
        # that protects you once a real LLM is feeding the pipeline.
        if validate:
            cases_as_dicts = [c.model_dump() for c in suite.cases]
            result = IRValidator().validate_suite(cases_as_dicts)
            if not result.ok:
                raise IRValidationError(result)
        body = [self._header(suite)]
        for case in suite.cases:
            body.append(self._render_case(case))
        return "\n\n".join(body) + "\n"

    # ---- file header / fixtures -------------------------------------
    def _header(self, suite: TestSuite) -> str:
        return f'''"""
Auto-generated by TaaS Translation Engine. DO NOT hand-edit.
Suite: {suite.suite_name}
Base URL: {suite.base_url}
Sources: {", ".join(sorted({c.source for c in suite.cases}))}
"""
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC

BASE_URL = "{suite.base_url}"


@pytest.fixture
def driver():
    opts = webdriver.ChromeOptions()
    opts.add_argument("--headless=new")
    # In production this points at the Selenoid/Grid hub, not a local driver:
    #   driver = webdriver.Remote("http://selenoid:4444/wd/hub", options=opts)
    drv = webdriver.Chrome(options=opts)
    drv.implicitly_wait(5)
    yield drv
    drv.quit()'''

    # ---- one test function per TestCase -----------------------------
    def _render_case(self, case: TestCase) -> str:
        lines = [
            f"# source={case.source} | category={case.category.value}",
            "@pytest.mark.{0}".format(case.category.value),
            f"def test_{case.slug()}(driver):",
            f'    """{case.name}"""',
        ]
        for step in case.steps:
            lines.extend("    " + ln for ln in self._render_step(step))
        return "\n".join(lines)

    # ---- one or more lines of code per TestStep ---------------------
    def _render_step(self, step: TestStep) -> list[str]:
        a = step.action
        cmt = f"# {step.description}" if step.description else ""

        if a == ActionType.NAVIGATE:
            url = step.value or "/"
            target = "BASE_URL" if url == "/" else f'BASE_URL + "{url}"'
            return [cmt, f"driver.get({target})"] if cmt else [f"driver.get({target})"]

        if a == ActionType.FILL:
            by, val = step.locator.as_by(), step.locator.value
            return self._with_cmt(cmt, [
                f'el = driver.find_element({by}, "{val}")',
                "el.clear()",
                f'el.send_keys("{self._esc(step.value)}")',
            ])

        if a == ActionType.CLICK:
            by, val = step.locator.as_by(), step.locator.value
            return self._with_cmt(cmt,
                [f'driver.find_element({by}, "{val}").click()'])

        if a == ActionType.SELECT:
            by, val = step.locator.as_by(), step.locator.value
            return self._with_cmt(cmt, [
                f'Select(driver.find_element({by}, "{val}"))'
                f'.select_by_visible_text("{self._esc(step.value)}")',
            ])

        if a == ActionType.WAIT:
            by, val = step.locator.as_by(), step.locator.value
            return self._with_cmt(cmt, [
                f"WebDriverWait(driver, {step.timeout}).until(",
                f'    EC.presence_of_element_located(({by}, "{val}")))',
            ])

        if a == ActionType.ASSERT_TEXT:
            by, val = step.locator.as_by(), step.locator.value
            return self._with_cmt(cmt, [
                f'el = driver.find_element({by}, "{val}")',
                f'assert "{self._esc(step.value)}" in el.text, '
                f'f"expected text not found: {{el.text!r}}"',
            ])

        if a == ActionType.ASSERT_VISIBLE:
            by, val = step.locator.as_by(), step.locator.value
            return self._with_cmt(cmt, [
                f"assert driver.find_element({by}, \"{val}\").is_displayed()",
            ])

        if a == ActionType.ASSERT_URL:
            return self._with_cmt(cmt, [
                f'assert "{self._esc(step.value)}" in driver.current_url',
            ])

        if a == ActionType.SCREENSHOT:
            return self._with_cmt(cmt, [
                'driver.save_screenshot('
                'f"/artifacts/{driver.session_id}.png")  # -> MinIO',
            ])

        if a == ActionType.SECURITY_SCAN:
            return self._with_cmt(cmt, [
                f'# DAST hook: enqueue OWASP ZAP scan against "{step.value}"',
                f'zap_scan(target=BASE_URL + "{step.value}")  '
                "# provided by conftest plugin",
            ])

        return [f"# (unhandled action: {a})"]

    @staticmethod
    def _with_cmt(cmt, lines):
        return ([cmt] + lines) if cmt else lines

    @staticmethod
    def _esc(s) -> str:
        return (s or "").replace("\\", "\\\\").replace('"', '\\"')
