"""
Intermediate Representation (IR) for the TaaS platform.

This is the single most important module in the system. EVERY test --
whether hand-built in the React Flow UI, derived from a Jira/Excel user story,
or generated by the AI codebase analyzer -- is normalized into this schema.

Why this matters:
  * The low-code UI reads/writes IR, never raw Selenium.
  * The AI's only job is to emit IR (structured data), never final code.
  * The Translation Engine deterministically renders IR -> pytest+Selenium.
This decoupling is what makes the platform low-code, auditable, and source-agnostic.
"""
from __future__ import annotations

from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class ActionType(str, Enum):
    """The vocabulary of test actions the low-code builder exposes as nodes."""
    NAVIGATE = "navigate"      # go to a URL
    FILL = "fill"              # type text into an input
    CLICK = "click"            # click an element
    SELECT = "select"          # choose a dropdown option
    WAIT = "wait"              # wait for an element / condition
    ASSERT_TEXT = "assert_text"        # element contains text
    ASSERT_VISIBLE = "assert_visible"  # element is visible
    ASSERT_URL = "assert_url"          # current URL matches
    SCREENSHOT = "screenshot"  # capture artifact
    SECURITY_SCAN = "security_scan"    # hand off to ZAP/SAST (DAST hook)


class Locator(BaseModel):
    """How to find an element. Mirrors Selenium's By strategies."""
    strategy: str = Field(..., description="id | name | css | xpath | link_text")
    value: str

    def as_by(self) -> str:
        mapping = {
            "id": "By.ID",
            "name": "By.NAME",
            "css": "By.CSS_SELECTOR",
            "xpath": "By.XPATH",
            "link_text": "By.LINK_TEXT",
        }
        return mapping.get(self.strategy, "By.CSS_SELECTOR")


class TestStep(BaseModel):
    """A single atomic action. One React Flow node == one TestStep."""
    action: ActionType
    locator: Optional[Locator] = None
    value: Optional[str] = None          # text to type, URL, expected text, etc.
    description: Optional[str] = None     # human-readable, shown in UI & report
    timeout: int = 10


class TestCategory(str, Enum):
    """Lets the dashboard slice coverage by intent."""
    HAPPY_PATH = "happy_path"
    EDGE_CASE = "edge_case"
    NEGATIVE = "negative"
    SECURITY = "security"


class TestCase(BaseModel):
    """An ordered sequence of steps with metadata about where it came from."""
    name: str
    category: TestCategory = TestCategory.HAPPY_PATH
    source: str = Field(..., description="story:PROJ-123 | code:LoginForm | manual")
    tags: List[str] = Field(default_factory=list)
    steps: List[TestStep]

    def slug(self) -> str:
        import re
        s = re.sub(r"[^a-zA-Z0-9]+", "_", self.name.lower()).strip("_")
        return s or "unnamed_test"


class TestSuite(BaseModel):
    """The merge point: story-derived + code-derived + manual tests, unified."""
    suite_name: str
    base_url: str
    cases: List[TestCase] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    def merge(self, other: "TestSuite") -> "TestSuite":
        """Combine two suites (e.g. story tests + codebase tests) into one."""
        return TestSuite(
            suite_name=self.suite_name,
            base_url=self.base_url or other.base_url,
            cases=self.cases + other.cases,
            metadata={**self.metadata, **other.metadata},
        )

    def coverage_summary(self) -> Dict[str, int]:
        """Feeds the homepage coverage/metrics widgets."""
        summary: Dict[str, int] = {c.value: 0 for c in TestCategory}
        for case in self.cases:
            summary[case.category.value] += 1
        summary["total"] = len(self.cases)
        return summary
