"""
Auto-generated by TaaS Translation Engine. DO NOT hand-edit.
Suite: Password Reset & Auth
Base URL: https://demo-app.local
Sources: code:LoginForm, story:CSV-1, story:PROJ-123
"""
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC

BASE_URL = "https://demo-app.local"


@pytest.fixture
def driver():
    opts = webdriver.ChromeOptions()
    opts.add_argument("--headless=new")
    # In production this points at the Selenoid/Grid hub, not a local driver:
    #   driver = webdriver.Remote("http://selenoid:4444/wd/hub", options=opts)
    drv = webdriver.Chrome(options=opts)
    drv.implicitly_wait(5)
    yield drv
    drv.quit()

# source=story:PROJ-123 | category=happy_path
@pytest.mark.happy_path
def test_story_happy_path_user_can_reset_password_via_email_link(driver):
    """Story happy path - User can reset password via email link"""
    # Open app for: User can reset password via email link
    driver.get(BASE_URL)
    # AC: User can enter their email address
    el = driver.find_element(By.NAME, "email")
    el.clear()
    el.send_keys("sample_value")
    # AC: User can click the reset button
    driver.find_element(By.CSS_SELECTOR, "button[type=submit]").click()
    # AC (verify): User should see a confirmation message: Reset link sent
    el = driver.find_element(By.CSS_SELECTOR, "body")
    assert "a confirmation message: Reset link sent" in el.text, f"expected text not found: {el.text!r}"
    # Capture final state
    driver.save_screenshot(f"/artifacts/{driver.session_id}.png")  # -> MinIO

# source=story:CSV-1 | category=happy_path
@pytest.mark.happy_path
def test_story_happy_path_login_with_valid_creds(driver):
    """Story happy path - Login with valid creds"""
    # Open app for: Login with valid creds
    driver.get(BASE_URL)
    # AC: User can enter email
    el = driver.find_element(By.NAME, "email")
    el.clear()
    el.send_keys("sample_value")
    # AC: User can enter password
    el = driver.find_element(By.NAME, "password")
    el.clear()
    el.send_keys("sample_value")
    # AC: User can click submit
    driver.find_element(By.CSS_SELECTOR, "button[type=submit]").click()
    # AC (verify): User should see Dashboard
    el = driver.find_element(By.CSS_SELECTOR, "body")
    assert "Dashboard" in el.text, f"expected text not found: {el.text!r}"
    # Capture final state
    driver.save_screenshot(f"/artifacts/{driver.session_id}.png")  # -> MinIO

# source=code:LoginForm | category=edge_case
@pytest.mark.edge_case
def test_edge_empty_fields_on_loginform(driver):
    """Edge - empty fields on LoginForm"""
    # Open component
    driver.get(BASE_URL)
    # Edge: leave 'email' empty
    el = driver.find_element(By.NAME, "email")
    el.clear()
    el.send_keys("")
    # Edge: leave 'password' empty
    el = driver.find_element(By.NAME, "password")
    el.clear()
    el.send_keys("")
    # Submit with empty fields
    driver.find_element(By.CSS_SELECTOR, "button[type=submit]").click()
    # Expect validation error
    assert driver.find_element(By.CSS_SELECTOR, ".error, [role=alert]").is_displayed()

# source=code:LoginForm | category=negative
@pytest.mark.negative
def test_negative_invalid_input_on_loginform(driver):
    """Negative - invalid input on LoginForm"""
    driver.get(BASE_URL)
    # Negative: invalid data in 'email'
    el = driver.find_element(By.NAME, "email")
    el.clear()
    el.send_keys("invalid!!!")
    # Negative: invalid data in 'password'
    el = driver.find_element(By.NAME, "password")
    el.clear()
    el.send_keys("invalid!!!")
    driver.find_element(By.CSS_SELECTOR, "button[type=submit]").click()
    # Should not navigate away on invalid input
    assert "/api/auth/login" in driver.current_url

# source=code:LoginForm | category=security
@pytest.mark.security
def test_security_injection_probe_on_loginform(driver):
    """Security - injection probe on LoginForm"""
    driver.get(BASE_URL)
    # Security: injection probe in 'email'
    el = driver.find_element(By.NAME, "email")
    el.clear()
    el.send_keys("' OR '1'='1")
    # Security: injection probe in 'password'
    el = driver.find_element(By.NAME, "password")
    el.clear()
    el.send_keys("' OR '1'='1")
    driver.find_element(By.CSS_SELECTOR, "button[type=submit]").click()
    # Hand off endpoint to OWASP ZAP for DAST scan
    # DAST hook: enqueue OWASP ZAP scan against "/api/auth/login"
    zap_scan(target=BASE_URL + "/api/auth/login")  # provided by conftest plugin
